[2023-11-24T18:38:30.108+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: COVID-19.Data_transform_and_load manual__2023-11-22T19:29:07.263785+00:00 [queued]>
[2023-11-24T18:38:30.124+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: COVID-19.Data_transform_and_load manual__2023-11-22T19:29:07.263785+00:00 [queued]>
[2023-11-24T18:38:30.125+0000] {taskinstance.py:1361} INFO - Starting attempt 12 of 12
[2023-11-24T18:38:30.144+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Data_transform_and_load> on 2023-11-22 19:29:07.263785+00:00
[2023-11-24T18:38:30.151+0000] {standard_task_runner.py:57} INFO - Started process 1055 to run task
[2023-11-24T18:38:30.154+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'COVID-19', 'Data_transform_and_load', 'manual__2023-11-22T19:29:07.263785+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmpgdm0y0qt']
[2023-11-24T18:38:30.157+0000] {standard_task_runner.py:85} INFO - Job 88: Subtask Data_transform_and_load
[2023-11-24T18:38:30.211+0000] {task_command.py:416} INFO - Running <TaskInstance: COVID-19.Data_transform_and_load manual__2023-11-22T19:29:07.263785+00:00 [running]> on host 3742b108fdc7
[2023-11-24T18:38:30.437+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='COVID-19' AIRFLOW_CTX_TASK_ID='Data_transform_and_load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-22T19:29:07.263785+00:00' AIRFLOW_CTX_TRY_NUMBER='12' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-22T19:29:07.263785+00:00'
[2023-11-24T18:38:30.801+0000] {base.py:73} INFO - Using connection ID 'postgres_connexion' for task execution.
[2023-11-24T18:38:31.143+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_etl.py:97: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_hospit['nbre_hospit_corona'] = df_hospit['nbre_hospit_corona'].fillna(0).astype(int)

[2023-11-24T18:38:31.159+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_etl.py:98: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_hospit['nbre_hospit_corona_h'] = df_hospit['nbre_hospit_corona_h'].fillna(0).astype(int)

[2023-11-24T18:38:31.174+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_etl.py:99: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_hospit['nbre_hospit_corona_f'] = df_hospit['nbre_hospit_corona_f'].fillna(0).astype(int)

[2023-11-24T18:38:31.176+0000] {logging_mixin.py:151} INFO - nbre_hospit_corona      int64
nbre_hospit_corona_h    int64
nbre_hospit_corona_f    int64
dtype: object
[2023-11-24T18:38:31.185+0000] {base.py:73} INFO - Using connection ID 'postgres_connexion' for task execution.
[2023-11-24T18:48:12.766+0000] {python.py:194} INFO - Done. Returned value was: Data inserted successfully
[2023-11-24T18:48:12.794+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=COVID-19, task_id=Data_transform_and_load, execution_date=20231122T192907, start_date=20231124T183830, end_date=20231124T184812
[2023-11-24T18:48:12.833+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-24T18:48:12.854+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
