[2023-11-24T15:40:32.272+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: COVID-19.Data_transform_and_load manual__2023-11-22T19:29:07.263785+00:00 [queued]>
[2023-11-24T15:40:32.288+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: COVID-19.Data_transform_and_load manual__2023-11-22T19:29:07.263785+00:00 [queued]>
[2023-11-24T15:40:32.289+0000] {taskinstance.py:1361} INFO - Starting attempt 8 of 8
[2023-11-24T15:40:32.311+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Data_transform_and_load> on 2023-11-22 19:29:07.263785+00:00
[2023-11-24T15:40:32.320+0000] {standard_task_runner.py:57} INFO - Started process 218 to run task
[2023-11-24T15:40:32.325+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'COVID-19', 'Data_transform_and_load', 'manual__2023-11-22T19:29:07.263785+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmpyt4txhmj']
[2023-11-24T15:40:32.328+0000] {standard_task_runner.py:85} INFO - Job 84: Subtask Data_transform_and_load
[2023-11-24T15:40:32.390+0000] {task_command.py:416} INFO - Running <TaskInstance: COVID-19.Data_transform_and_load manual__2023-11-22T19:29:07.263785+00:00 [running]> on host 3742b108fdc7
[2023-11-24T15:40:32.711+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='COVID-19' AIRFLOW_CTX_TASK_ID='Data_transform_and_load' AIRFLOW_CTX_EXECUTION_DATE='2023-11-22T19:29:07.263785+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-22T19:29:07.263785+00:00'
[2023-11-24T15:40:33.213+0000] {base.py:73} INFO - Using connection ID 'postgres_connexion' for task execution.
[2023-11-24T15:40:33.651+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_etl.py:73: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_passage['nbre_pass_corona'] = df_passage['nbre_pass_corona'].fillna(0).astype(int)

[2023-11-24T15:40:33.694+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_etl.py:74: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_passage['nbre_pass_tot'] = df_passage['nbre_pass_tot'].fillna(0).astype(int)

[2023-11-24T15:40:33.720+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_etl.py:75: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_passage['nbre_pass_corona_h'] = df_passage['nbre_pass_corona_h'].fillna(0).astype(int)

[2023-11-24T15:40:33.745+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_etl.py:76: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_passage['nbre_pass_corona_f'] = df_passage['nbre_pass_corona_f'].fillna(0).astype(int)

[2023-11-24T15:40:33.771+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_etl.py:77: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_passage['nbre_pass_tot_h'] = df_passage['nbre_pass_tot_h'].fillna(0).astype(int)

[2023-11-24T15:40:33.800+0000] {warnings.py:109} WARNING - /opt/***/dags/dag_etl.py:78: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_passage['nbre_pass_tot_f'] = df_passage['nbre_pass_tot_f'].fillna(0).astype(int)

[2023-11-24T15:40:33.803+0000] {logging_mixin.py:151} INFO - nbre_pass_corona      int64
nbre_pass_tot         int64
nbre_pass_corona_h    int64
nbre_pass_corona_f    int64
nbre_pass_tot_h       int64
nbre_pass_tot_f       int64
dtype: object
[2023-11-24T15:40:33.818+0000] {base.py:73} INFO - Using connection ID 'postgres_connexion' for task execution.
[2023-11-24T15:50:57.203+0000] {python.py:194} INFO - Done. Returned value was: Data inserted successfully
[2023-11-24T15:50:57.237+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=COVID-19, task_id=Data_transform_and_load, execution_date=20231122T192907, start_date=20231124T154032, end_date=20231124T155057
[2023-11-24T15:50:57.304+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-24T15:50:57.326+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
